import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./providers";
import Navbar from "./_navigation/navbar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning="true">
      <head></head>
      <body className={inter.className} cz-shortcut-listen="true">
        {/* remove the "cz-shortcut-listen" in prod, it's only to suppress hydration warnings from the colorzilla extension */}
        <Providers>
          <header
            className="sticky top-0 border-b flex flex-row items-center"
            style={{ minHeight: "6vh" }}
          >
            <Navbar />
          </header>
          <main>{children}</main>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
